packages:
  - "apps/*"
  - "packages/*"
  - "tool/*"

catalog:
  tailwindcss: ^4.0.8
  typescript: ^5.7.3

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19
    "@types/react-dom": ^19
